### PR TITLE
Remove mappings

### PR DESCRIPTION
**Pull request by rettigl**
Removes the mappings and default units, and rather gets values directly from the ELN paths with new mechanism.

Would be good to add some tests for the ELN functionality

### CODE REVIEW

**Comment by rettigl** [comment]
Not sure why tests fail.Maybe the test data don't include units?

**Comment by rettigl** [comment]
An updated config file for specsscan is here: https://github.com/OpenCOMPES/specsanalyzer/pull/53

**Review by lukaspie — APPROVED** [review]
To me, this makes sense and it also makes the reading of instrument metadata and ELN data consistent. Will probably do the same for the XPS reader.

**Comment by domna** [comment]
I added some tests for the eln data and updated the config file for it. I also stripped the eln file to only check a certain amount of fields (as this is not the eln example anymore I think it's fine to only use some fields for checking).

With this I will merge into the other PR.

**Pull request merged**
